version: "3.9"

services:
  client:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - "./client:/usr/src/app"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
